build:
  stage: build
  only:
    - ci-cd
  before_script:
    - echo 'build starts'
    - chmod +x ./gradlew
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  tags:
    - ssafy
  when: manual
