stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/

build:
  stage: build
  only:
    - ci-cd
  before_script:
    - echo 'build starts'
    - cd ./backend/ssafyBigswing/
    - chmod +x ./gradlew
  script:
    - ./gradlew clean build
    - docker build -t springboot . # Docker 이미지 빌드
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - ssafy
  when: manual

dev_deploy:
  stage: deploy
  only:
    - ci-cd
  before_script:
    - echo 'deploy starts'
  script:
    - docker run -d -p 8080:8080 --name springboot-app springboot # Docker 컨테이너 실행
  tags:
    - ssafy
  when: manual
