spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 160473970613-kedt5h9uf0i2cepc82lhkpvmih1dgc3u.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: jzQ_Z_TqlmAVqPcgNCwr
            client-secret: eseJBAMxn2
            redirect-uri: http://localhost:8080/api/auth/login/naver
            authorization-grant-type: authorization_code
            scope: email, profile_image, nickname
            client-name: Naver

          kakao:
            client-id: 58eed44d11c6af52c6a68c04e0535346
            client-secret: bBPBGpVCVBztPXD2OW5HeBNtTUUNU5YY
            redirect-uri: http://localhost:8080/api/auth/login/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_image, profile_nickname, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id